import type { Metadata } from "next";
import "@ritwikdax/uicc/styles.css";
import "./globals.css";
import AllContext from "./context/AllContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body>
        <AllContext>{children}</AllContext>
      </body>
    </html>
  );
}
